<a href="https://colab.research.google.com/github/chiraglamba27/UCS420_Chirag_Lamba_1024170138_Assignments/blob/main/Assign_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

print("Q1")
temp = np.array([25, 28, 31, 35, 38, 27, 33, 40])

adj = temp + 2
print("a.", adj)

fah = temp * 9 / 5 + 32
print("b.", fah)

hot = temp[temp > 32]
print("c.", hot)

print("d.", np.sum(temp > 32))

print()
print("Q2")
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]])

print("a.", steps.sum())
print("b.", steps.mean())
print("c.", steps.max(), steps.min())
print("d.", steps.sum(axis=0))
print("e.", steps.sum(axis=1))
pos = np.unravel_index(steps.argmax(), steps.shape)
print("f.", steps.argmax(), pos)

print()
print("Q3")
original = np.array([1, 2, 3, 4, 5, 6])

subset = original[1:4]
subset[0] = 999
print(original)
print(subset)

original = np.array([1, 2, 3, 4, 5, 6])
cp = original[1:4].copy()
cp[0] = 500
print(original)
print(cp)

m = np.arange(1, 13).reshape(3, 4)
print(m)

print(m[0])
print(m[-1])
print(m[:, 1])
print(m[0:2, 1:3])

fl = m.flatten()
rv = m.ravel()
print(fl)
print(rv)

rv[0] = 100
print(rv)
print(m)

m = np.arange(1, 13).reshape(3, 4)
fl = m.flatten()
fl[0] = 100
print(fl)
print(m)

m = np.arange(1, 13).reshape(3, 4)
print(m.shape, m.ndim, m.size, m.dtype)

print()
print("Q4")
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]])
y = np.array([40, 65, 30, 85])

print("a.", X.shape, X.ndim)

print("b.")
print(X.T)

xtx = X.T @ X
print("c.")
print(xtx)

print("d.", np.linalg.det(xtx))
inv = np.linalg.inv(xtx)
print(inv)

xty = X.T @ y
b = inv @ xty
print("e.", b)

nu = np.array([5, 40, 7])
pred = nu @ b
print("g.", pred)

Q1
a. [27 30 33 37 40 29 35 42]
b. [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
c. [35 38 33 40]
d. 4

Q2
a. 84200
b. 7016.666666666667
c. 9500 4500
d. [26500 27300 30400]
e. [18300 24500 14400 27000]
f. 11 (np.int64(3), np.int64(2))

Q3
[  1 999   3   4   5   6]
[999   3   4]
[1 2 3 4 5 6]
[500   3   4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[ 9 10 11 12]
[ 2  6 10]
[[2 3]
 [6 7]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[100   2   3   4   5   6   7   8   9  10  11  12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[100   2   3   4   5   6   7   8   9  10  11  12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4) 2 12 int64

Q4
a. (4, 3) 2
b.
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
c.
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
d. 753700.000000011
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
e. [-0.15921454  0.140838